### ISSUE TITLE
How hide back face

### ISSUE THREAD

**Issue by rhoulay** [tidwall/pinhole#1]
If it's possible hide the back face, and how?

**Comment by tidwall** [comment]
I'm not sure what you mean by "back face". Are you referring to the z depth where objects are no long visible?

**Comment by rhoulay** [comment]
I mean hide back faces so that you only see faces when its normal is facing the camera.

**Comment by tidwall** [comment]
Oh, ok that makes sense. Right now there isn’t a way to do that and everything just displays as a simple wireframe.
